OUTER_SET ps_max_id = -1
OUTER_SET ps_split = 0
OUTER_SET ps_text_cols = 0
ACTION_IF FILE_EXISTS_IN_GAME ~hpclass.2da~ THEN BEGIN
  OUTER_SET ps_split = 1
  COPY_EXISTING ~clastext.2da~ ~override~
    COUNT_2DA_COLS ps_text_cols
    READ_2DA_ENTRIES_NOW ~ps_rows~ ps_text_cols
    FOR (ps_i=0; ps_i<ps_rows; ++ps_i) BEGIN
      READ_2DA_ENTRY_FORMER ~ps_rows~ ps_i 1 ps_id
      PATCH_IF IS_AN_INT ~%ps_id%~ AND ps_id > ps_max_id BEGIN SET ps_max_id=ps_id END
    END
  BUT_ONLY
END ELSE BEGIN
  OUTER_SET ps_cols=0
  COPY_EXISTING ~classes.2da~ ~override~
    COUNT_2DA_COLS ps_cols
    READ_2DA_ENTRIES_NOW ~ps_rows~ ps_cols
    FOR (ps_i=0; ps_i<ps_rows; ++ps_i) BEGIN
      READ_2DA_ENTRY_FORMER ~ps_rows~ ps_i 6 ps_id
      PATCH_IF IS_AN_INT ~%ps_id%~ AND ps_id > ps_max_id BEGIN SET ps_max_id=ps_id END
    END
  BUT_ONLY
END
ACTION_IF ps_max_id < 0 THEN BEGIN FAIL @3 END
ACTION_IF ps_max_id > 249 THEN BEGIN FAIL @6 END

OUTER_SET ps_seer_id=ps_max_id+1
OUTER_SET ps_shaper_id=ps_max_id+2
OUTER_SET ps_kineticist_id=ps_max_id+3
OUTER_SET ps_egoist_id=ps_max_id+4
OUTER_SET ps_nomad_id=ps_max_id+5
OUTER_SET ps_telepath_id=ps_max_id+6
