DEFINE_PATCH_FUNCTION CIPHER_FIX_THAC0_EFFECTS
STR_VAR
  ci_power_resref = ~~
BEGIN
  READ_LONG 0x64 ci_power_header_offset
  READ_SHORT 0x68 ci_power_header_count
  READ_LONG 0x6a ci_power_effect_offset

  FOR (ci_power_header_index = 0; ci_power_header_index < ci_power_header_count; ++ci_power_header_index) BEGIN
    SET ci_power_header = ci_power_header_offset + (ci_power_header_index * 0x28)
    READ_SHORT (ci_power_header + 0x1e) ci_power_effect_count
    READ_SHORT (ci_power_header + 0x20) ci_power_first_effect

    FOR (ci_power_effect_index = 0; ci_power_effect_index < ci_power_effect_count; ++ci_power_effect_index) BEGIN
      SET ci_power_effect = ci_power_effect_offset + ((ci_power_first_effect + ci_power_effect_index) * 0x30)
      READ_SHORT ci_power_effect ci_power_opcode
      READ_BYTE (ci_power_effect + 0x02) ci_power_target
      PATCH_IF ci_power_opcode = 54 BEGIN
        PATCH_IF ~%ci_power_resref%~ STRING_EQUAL_CASE ~CI5BINS~ BEGIN
          PATCH_IF ci_power_target = 2 BEGIN
            WRITE_LONG (ci_power_effect + 0x04) 3
          END ELSE PATCH_IF ci_power_target = 9 BEGIN
            WRITE_LONG (ci_power_effect + 0x04) (0 - 3)
          END
        END ELSE PATCH_IF ~%ci_power_resref%~ STRING_EQUAL_CASE ~CI7TPAR~ BEGIN
          PATCH_IF ci_power_target = 9 BEGIN
            WRITE_LONG (ci_power_effect + 0x04) (0 - 4)
          END
        END
      END
    END
  END
END

COPY_EXISTING ~CI5BINS.spl~ ~override~
  LPF CIPHER_FIX_THAC0_EFFECTS STR_VAR ci_power_resref = ~CI5BINS~ END
BUT_ONLY

COPY_EXISTING ~CI7TPAR.spl~ ~override~
  LPF CIPHER_FIX_THAC0_EFFECTS STR_VAR ci_power_resref = ~CI7TPAR~ END
BUT_ONLY
